#!/bin/bash

#Backup user's home directory

user=$(whoami)
input=/home/$user
output=/data/${user}_home_$(date +%Y-%m-%d_%H%M%S).tar.gz

tar -czvf $output $input 2> /dev/null

echo "Backup of $input completed. "

ls -l $output
