#!/bin/bash

#Backup user directory

user=$(whoami)
input=/home/$user
output=/data/${user}_home_$(date +%Y-%m-%d_%H%M%S).tar.gz

#The function total_files reports a total number of files from a given directory

function total_files {
        find $1 -type f | wc -l
}

#Function total_directories reports total number of directories

function total_directories {
     find $1 -type d| wc -l
}

tar -czvf $output $input 2> /dev/null

echo -n "Files included: "
total_files $input
echo -n "Directories included: "
total_directories $input

echo "Backup of $input complete!"

echo "Details about the output backup file: "
ls -l|$output
