#!/bin/bash

num_a=400
num_b=200
num_c=100


if [ $num_a -lt $num_b ]; then
    echo "$num_a is less than $num_b "
elif [ $num_a -lt $num_c ]; then
    echo "$num_a -lt $num_c" 
elif [ $num_b -lt $num_a ]; then
    echo "$num_b is less than $num_a"
elif [ $num_c -lt $num_b]; then
    echo "$num_c is less than $num_a"
elif [ $num_c -lt $num_a]; then
    echo "$num_c is less than $num_a"
else
    echo "$num_a is greater than $num_b "
fi
